import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./Provider";
// import { Provider } from "react-redux";
// import store from "../store";

import HomeComponent from "./MyComponents/HomeComponent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        <Providers>
          <div className="grid lg:grid-cols-[300px,1fr] h-screen max-h-screen">
            <section className="bg-white">
              <HomeComponent />
            </section> 
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
